--- #YAML:1.0
name:               SVN-Utils-ClientIP
version:            0.01
abstract:           Get the client's IP address in a Subversion Hook
author:
    - Mike Schilli <cpan@perlmeister.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Proc::Info::Environment:  0.01
    Proc::ProcessTable:   0.4
    Test::Harness:        3.21
resources:
    repository:  http://github.com/mschilli/svn-utils-clientip-perl
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
